module Evergreen.Migrate.V8 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.com/docs/evergreen> for more info.

-}

import Evergreen.V6.Types
import Evergreen.V8.Types
import Lamdera.Migrations exposing (..)


frontendModel : Evergreen.V6.Types.FrontendModel -> ModelMigration Evergreen.V8.Types.FrontendModel Evergreen.V8.Types.FrontendMsg
frontendModel old =
    ModelUnchanged


backendModel : Evergreen.V6.Types.BackendModel -> ModelMigration Evergreen.V8.Types.BackendModel Evergreen.V8.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V6.Types.FrontendMsg -> MsgMigration Evergreen.V8.Types.FrontendMsg Evergreen.V8.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V6.Types.ToBackend -> MsgMigration Evergreen.V8.Types.ToBackend Evergreen.V8.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V6.Types.BackendMsg -> MsgMigration Evergreen.V8.Types.BackendMsg Evergreen.V8.Types.BackendMsg
backendMsg old =
    MsgMigrated ( migrate_Types_BackendMsg old, Cmd.none )


toFrontend : Evergreen.V6.Types.ToFrontend -> MsgMigration Evergreen.V8.Types.ToFrontend Evergreen.V8.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_BackendMsg : Evergreen.V6.Types.BackendMsg -> Evergreen.V8.Types.BackendMsg
migrate_Types_BackendMsg old =
    case old of
        Evergreen.V6.Types.ClientConnected p0 p1 ->
            Evergreen.V8.Types.ClientConnected p0 p1

        Evergreen.V6.Types.ClientDisconnected p0 p1 ->
            Evergreen.V8.Types.ClientDisconnected p0 p1

        Evergreen.V6.Types.GotMetaResponse p0 ->
            Evergreen.V8.Types.GotMetaResponse p0

        Evergreen.V6.Types.GotPackageResponse p0 ->
            Evergreen.V8.Types.GotPackageResponse p0
